/* AIP-C01 Study Hub — content data.
   Loaded as a global (no fetch) so the app works from file:// on any device, offline.
   Grow it by asking Kiro: "add 20 quiz questions and 15 flashcards to the app." */
window.DATA = {
  exam: {
    name: "AWS Certified Generative AI Developer – Professional",
    code: "AIP-C01",
    date: "2026-10-19",
    start: "2026-09-05",
    questions: 75,
    minutes: 180,
    pass: 750,
  },

  domains: [
    { id: 1, name: "FM Integration, Data & Compliance", weight: 31 },
    { id: 2, name: "Implementation & Integration", weight: 26 },
    { id: 3, name: "AI Safety, Security & Governance", weight: 20 },
    { id: 4, name: "Operational Efficiency & Optimization", weight: 12 },
    { id: 5, name: "Testing, Validation & Troubleshooting", weight: 11 },
  ],

  // Week blocks. The app finds today's date within a week and shows that day's task.
  weeks: [
    {
      n: 0, label: "Setup", start: "2026-09-05", end: "2026-09-06",
      focus: "Get set up + baseline", udemy: "Section 1 (start)", lab: "Lab 1: Converse API",
      days: {
        Fri: { t: "Get set up and see the lay of the land", s: [
          "Read the Home tab's daily ritual here - the whole method is just 3 steps a day.",
          "Tap Cheat Sheets and skim the 5 domain titles and their % weights. Domains 1 and 2 are 57% of the exam.",
          "Log in to AWS and switch on the models: Console -> search 'Bedrock' -> Model access -> enable a Claude model and 'Titan Text Embeddings V2' in region us-east-1. Not logged in? Type to Kiro: 'help me sign in to AWS'.",
        ] },
        Sat: { t: "Your first hands-on + a baseline test", s: [
          "Do Lab 1: type to Kiro 'Start Lab 1'. It walks you through calling an AI model on AWS in about 30 minutes. It is fine if it feels new.",
          "Open your Udemy course, Section 1, and watch 'Amazon Bedrock Overview' and 'Hands-On with the Bedrock Playground'.",
          "Sit Udemy Practice Exam 1 as a baseline. Expect 30-50% - that is normal and just shows your start point. Tell Kiro 'log my practice exam: X%'.",
        ] },
        Sun: { t: "Learn from the baseline, get used to the format", s: [
          "Go through every question you got wrong on Practice Exam 1. For each, ask Kiro: 'explain why the correct answer is right, simply.'",
          "In the app, tap Quiz -> Domain 1 and answer 5 questions to feel the format.",
          "Tell Kiro 'log my misses' so the app starts tracking your weak spots.",
        ] },
      },
    },
    {
      n: 1, label: "Domain 1a", start: "2026-09-07", end: "2026-09-13",
      focus: "Bedrock, model selection, data pipelines", udemy: "Section 1 + start Section 2",
      lab: "Extend Lab 1 (compare models)",
      days: {
        Mon: { t: "How to call a foundation model (the Converse API)", s: [
          "Watch Udemy Section 1: 'Amazon Bedrock Overview' and 'More Depth on the Bedrock Converse API'.",
          "Read Cheat Sheets -> Domain 1 (the Bedrock, Converse API and maxTokens points).",
          "Redo Lab 1 and compare two models: tell Kiro 'Start Lab 1 and help me compare two models.'",
          "Quiz -> Domain 1 (5 questions), then tell Kiro 'log my misses.' Done when you can say what the Converse API is in one sentence.",
        ] },
        Tue: { t: "Picking the right model (cost vs capability)", s: [
          "Watch Udemy Section 4 'Cost-Effective Model Selection' and the Section 1 fine-tuning intro.",
          "Read Cheat Sheets -> Domain 1 'RAG vs fine-tune' and the model points.",
          "Quiz -> Domain 1 (5 questions); tell Kiro 'log my misses.'",
        ] },
        Wed: { t: "Making it reliable when a region is busy", s: [
          "Watch Udemy Section 4 'Amazon Bedrock Cross-Region Inference' and Section 6 'Step Functions Circuit Breaker Pattern'.",
          "Read Cheat Sheets -> Domain 1 'Cross-Region Inference'.",
          "Ask Kiro: 'explain cross-region inference profiles simply, like I will be tested.' Then Quiz -> Domain 1; log misses.",
        ] },
        Thu: { t: "Fine-tuning vs RAG (and the cheap way, LoRA)", s: [
          "Watch Udemy Section 1 'Fine-Tuning Foundation Models', 'Low-Rank Adaptation (LoRA)', 'Retrieval-Augmented Generation'.",
          "Read Cheat Sheets -> Domain 1 RAG-vs-fine-tune, then ask Kiro 'give me one scenario where RAG wins and one where fine-tuning wins.'",
          "Quiz -> Domain 1; log misses.",
        ] },
        Fri: { t: "Getting your data ready for the model", s: [
          "Watch Udemy Section 2: 'SageMaker Data Wrangler', 'AWS Glue', 'Amazon Comprehend', 'AWS Transcribe'.",
          "Read Cheat Sheets -> Domain 1 data-pipeline points and the Services sheet (data pipeline group).",
          "Quiz -> Domain 1; log misses.",
        ] },
        Sat: { t: "Catch up and fix what feels shaky", s: [
          "Open Weak Areas and tap 'Drill these now'.",
          "Re-watch any Section 1-2 lecture that did not land; ask Kiro to 're-explain [topic] simply.'",
          "Tell Kiro 'update my tracker' with how confident you feel (0-3) on this week's topics.",
        ] },
        Sun: { t: "Lock in Domain 1a", s: [
          "Quiz -> Drill weak areas (warm-up).",
          "Then tell Kiro 'give me a 15-question Domain 1 mock' and answer it.",
          "Tell Kiro 'log my misses and update my tracker.' Done when you are 2+/3 on this week's topics.",
        ] },
      },
    },
    {
      n: 2, label: "Domain 1b", start: "2026-09-14", end: "2026-09-20",
      focus: "RAG, vector stores, retrieval, prompts", udemy: "Finish Section 2",
      lab: "Lab 2: RAG Knowledge Base",
      days: {
        Mon: { t: "Build a RAG app (give the AI your own documents)", s: [
          "Do Lab 2: tell Kiro 'Start Lab 2' - you build a Bedrock Knowledge Base over sample docs and query it.",
          "For a preview, watch Udemy Section 1 'Bedrock Knowledge Bases' and 'Hands-On with Knowledge Bases'.",
          "Done when you can ask your Knowledge Base a question and get an answer with a citation.",
        ] },
        Tue: { t: "Where the AI's memory lives (vector stores)", s: [
          "Watch Udemy Section 2 vector-store lectures: OpenSearch, Aurora pgvector, S3 Vectors, DynamoDB.",
          "Read Cheat Sheets -> Domain 1 'Vector store'. Ask Kiro 'when would I pick OpenSearch vs Aurora pgvector vs S3 Vectors?'",
          "Quiz -> Domain 1; log misses.",
        ] },
        Wed: { t: "Chunking + embeddings (why RAG answers are good or bad)", s: [
          "Watch Udemy Section 1 'Pre-Retrieval and Chunking Strategies', 'Managing Chunking Strategies', 'Optimizing your Vector Store and Embeddings'.",
          "Read Cheat Sheets -> Domain 1 'Chunking' and 'Embeddings'.",
          "Quiz -> Domain 1; log misses.",
        ] },
        Thu: { t: "Getting better search results (hybrid search + rerankers)", s: [
          "Watch Udemy Section 1 'Evaluating RAG Performance' and the Section 2 're-ranker' lecture.",
          "Read Cheat Sheets -> Domain 1 (hybrid search / reranker). Ask Kiro 'explain hybrid search and a reranker simply.'",
          "Quiz -> Domain 1; log misses.",
        ] },
        Fri: { t: "Writing good prompts and managing them", s: [
          "Watch Udemy Section 1 'Intro to Prompt Engineering', 'Prompt Best Practices', 'Amazon Bedrock Prompt Management'.",
          "Read Cheat Sheets -> Domain 1 (prompt engineering + Prompt Management).",
          "Quiz -> Domain 1; log misses.",
        ] },
        Sat: { t: "Chaining prompts together (Bedrock Prompt Flows)", s: [
          "Watch Udemy Section 1 'Bedrock Prompt Flows' and 'Enforcing Use of Structured Data'.",
          "Open your PromptChaining.json (in the AIP-Materials folder) and ask Kiro to walk you through what it does.",
          "Quiz -> Domain 1; log misses.",
        ] },
        Sun: { t: "Big consolidation - Domain 1 is 31% of the exam", s: [
          "Quiz -> Drill weak areas (warm-up).",
          "Tell Kiro 'give me a 25-question full Domain 1 mock' and time yourself.",
          "Log misses + update tracker. Done when you can describe a full RAG pipeline out loud.",
        ] },
      },
    },
    {
      n: 3, label: "Domain 2", start: "2026-09-21", end: "2026-09-27",
      focus: "Agents, deployment, integration", udemy: "Sections 3, 5, 6",
      lab: "Lab 3: Agent on AgentCore",
      days: {
        Mon: { t: "Build an AI agent (it uses tools on its own)", s: [
          "Do Lab 3: tell Kiro 'Start Lab 3' - build an agent on AgentCore with a tool via Gateway.",
          "For a preview, watch Udemy Section 3 'Amazon AgentCore Introduction' and 'Lab: Amazon Bedrock AgentCore Harnesses'.",
          "Done when your agent calls your tool and returns an answer.",
        ] },
        Tue: { t: "Multi-agent systems + how agents talk to tools (MCP)", s: [
          "Watch Udemy Section 3 'Multi-Agent Workflows', 'Strands Agents', 'Agent Squad', 'Model Context Protocol (MCP)'.",
          "Read Cheat Sheets -> Domain 2 (agents/AgentCore/MCP). Ask Kiro 'what is the difference between Strands, Agent Squad, and AgentCore?'",
          "Quiz -> Domain 2; log misses.",
        ] },
        Wed: { t: "How to deploy models + keep agents safe", s: [
          "Watch Udemy Section 5 'Optimizing Foundation Model Deployments' and Section 3 'Short and Long-Term Agent Memory'.",
          "Read Cheat Sheets -> Domain 2 (deployment choices + agent safety).",
          "Quiz -> Domain 2; log misses.",
        ] },
        Thu: { t: "Connecting the model to apps (APIs, streaming)", s: [
          "Watch Udemy Section 6 'AWS Lambda', 'Amazon API Gateway', 'AWS Step Functions' and Section 4 'Exponential Backoff and Connection Pooling'.",
          "Read Cheat Sheets -> Domain 2 (FM API integration + routing).",
          "Quiz -> Domain 2; log misses.",
        ] },
        Fri: { t: "Plugging AI into a real business (enterprise integration)", s: [
          "Watch Udemy Section 6 'Amazon EventBridge', 'Amazon SQS', 'AWS Outposts', 'AWS Wavelength', 'AWS CodePipeline'.",
          "Read Cheat Sheets -> Domain 2 (enterprise integration). Ask Kiro 'when do I use Outposts vs Wavelength?'",
          "Quiz -> Domain 2; log misses.",
        ] },
        Sat: { t: "The AI helper services (Q Developer, Q Business)", s: [
          "Watch Udemy Section 6 'AWS Amplify' and Section 3 'Amazon Q Business', 'Amazon Q Apps'.",
          "Read Cheat Sheets -> Services (the ML/GenAI group).",
          "Quiz -> Domain 2; log misses.",
        ] },
        Sun: { t: "Consolidate Domain 2 - you have now covered 57% of the exam", s: [
          "Quiz -> Drill weak areas (warm-up).",
          "Tell Kiro 'give me a 20-question Domain 2 mock.'",
          "Log misses + update tracker.",
        ] },
      },
    },
    {
      n: 4, label: "Domain 3", start: "2026-09-28", end: "2026-10-04",
      focus: "Safety, security, governance", udemy: "Sections 7 (part) + 8",
      lab: "Lab 4: Guardrails + PII",
      days: {
        Mon: { t: "Build safety controls (Guardrails + PII)", s: [
          "Do Lab 4: tell Kiro 'Start Lab 4' - add Bedrock Guardrails and a PII filter, and see the CloudWatch logging gap.",
          "For a preview, watch Udemy Section 1 'Bedrock Guardrails' and 'Hands-On with Bedrock Guardrails'.",
          "Done when your guardrail blocks a bad prompt and you know where PII still leaks (the logs).",
        ] },
        Tue: { t: "Blocking bad input and output", s: [
          "Watch Udemy Section 1 'Token-Level Redaction' and Section 3 'Humans in the Loop'.",
          "Read Cheat Sheets -> Domain 3 (Guardrails + prompt injection).",
          "Quiz -> Domain 3; log misses.",
        ] },
        Wed: { t: "Stopping the AI from making things up", s: [
          "Watch Udemy Section 1 'Evaluating RAG Performance' again, focusing on grounding.",
          "Read Cheat Sheets -> Domain 3 (hallucination fix: grounding, confidence, JSON schema).",
          "Quiz -> Domain 3; log misses.",
        ] },
        Thu: { t: "Protecting data and PII", s: [
          "Watch Udemy Section 8 'AWS KMS', 'Amazon Macie', 'AWS PrivateLink', the VPC lectures, and Section 2 'Amazon Comprehend'.",
          "Read Cheat Sheets -> Domain 3 (data security; Comprehend vs Macie).",
          "Quiz -> Domain 3; log misses.",
        ] },
        Fri: { t: "Governance: proving what the AI did", s: [
          "Watch Udemy Section 7 'AWS CloudTrail', 'AWS Lake Formation' and Section 5 'SageMaker Lineage Tracking', 'Model Registry'.",
          "Read Cheat Sheets -> Domain 3 (governance).",
          "Quiz -> Domain 3; log misses.",
        ] },
        Sat: { t: "Responsible AI (fairness, transparency)", s: [
          "Watch Udemy Section 7 'Principles of Responsible AI', 'Bedrock Agent Tracing' and Section 5 'Model Monitor and Clarify'.",
          "Read Cheat Sheets -> Domain 3 (Responsible AI). Ask Kiro 'how do I prove a model is not biased?'",
          "Quiz -> Domain 3; log misses.",
        ] },
        Sun: { t: "Consolidate Domain 3", s: [
          "Quiz -> Drill weak areas (warm-up).",
          "Tell Kiro 'give me a 20-question Domain 3 mock.'",
          "Log misses + update tracker.",
        ] },
      },
    },
    {
      n: 5, label: "Domains 4 + 5", start: "2026-10-05", end: "2026-10-11",
      focus: "Optimize, monitor, evaluate, troubleshoot", udemy: "Sections 4, 7, 9",
      lab: "Lab 5: Evaluate + observe + break/fix",
      days: {
        Mon: { t: "Measure, watch, and fix your AI app", s: [
          "Do Lab 5: tell Kiro 'Start Lab 5' - run a Bedrock evaluation, add CloudWatch/X-Ray monitoring, then break something and fix it.",
          "For a preview, watch Udemy Section 7 'Amazon Bedrock Model Evaluations' and 'CloudWatch Logs'.",
          "Done when you can read token usage in CloudWatch and diagnose one broken prompt.",
        ] },
        Tue: { t: "Spending less (token + cost efficiency)", s: [
          "Watch Udemy Section 4 'Token Efficiency' and 'Maximizing Resource Utilization and Throughput'.",
          "Read Cheat Sheets -> Domain 4 (token efficiency, CountTokens).",
          "Quiz -> Domain 4; log misses.",
        ] },
        Wed: { t: "Going faster (caching + latency + settings)", s: [
          "Watch Udemy Section 4 'Intelligent Caching Systems for GenAI' and 'Building Responsive AI Systems'.",
          "Read Cheat Sheets -> Domain 4 (caching, latency, temperature/top-k/top-p).",
          "Quiz -> Domain 4; log misses.",
        ] },
        Thu: { t: "Watching it in production (monitoring)", s: [
          "Watch Udemy Section 7 'CloudWatch and GenAI Monitoring' and 'AWS X-Ray'.",
          "Read Cheat Sheets -> Domain 4 (monitoring).",
          "Quiz -> Domain 4; log misses.",
        ] },
        Fri: { t: "Testing AI quality (evaluation)", s: [
          "Watch Udemy Section 7 'Evaluation Techniques for Foundation Models' and 'Evaluating LLMs with ROUGE, BLEU, and BERT scores'.",
          "Read Cheat Sheets -> Domain 5 (metrics, ROUGE, LLM-as-judge). Ask Kiro 'what does ROUGE measure vs faithfulness?'",
          "Quiz -> Domain 5; log misses.",
        ] },
        Sat: { t: "Fixing common failures (troubleshooting)", s: [
          "Watch Udemy Section 7 'Deployment Validation Systems' and review Bedrock Agent Tracing.",
          "Read Cheat Sheets -> Domain 5 (the 3 common failures + fixes).",
          "Quiz -> Domain 5; log misses.",
        ] },
        Sun: { t: "Consolidate - all 5 domains now covered", s: [
          "Quiz -> Drill weak areas (warm-up).",
          "Tell Kiro 'give me a 15-question Domain 4 and 5 mock.'",
          "Log misses + update tracker.",
        ] },
      },
    },
    {
      n: 6, label: "Mocks + Review", start: "2026-10-12", end: "2026-10-18",
      focus: "Practice exams + close gaps", udemy: "Practice Exams 1 & 2 + section quizzes",
      lab: "None - exam prep",
      days: {
        Mon: { t: "First full timed practice exam", s: [
          "Sit a Udemy Practice Exam properly: 75 questions, 180 minutes, no notes.",
          "Score it. Tell Kiro 'log my practice exam: X%, weak on [domains]'.",
          "Put every wrong topic into Weak Areas (tell Kiro 'log these misses').",
        ] },
        Tue: { t: "Fix what you missed", s: [
          "Ask Kiro 'teach me only what I missed on the mock', one topic at a time.",
          "Quiz -> Drill weak areas until they stop coming up.",
        ] },
        Wed: { t: "Second full timed practice exam", s: [
          "Sit the other Udemy Practice Exam: 75 questions, 180 minutes, timed.",
          "Score it and log misses. Your target is 80%+.",
        ] },
        Thu: { t: "Fix misses + practice the tricky question types", s: [
          "Remediate mock 2 with Kiro.",
          "Practice the new question types: tell Kiro 'give me 5 ordering and 5 matching questions' (no partial credit on these).",
        ] },
        Fri: { t: "Targeted final drills", s: [
          "Quiz -> Drill weak areas across all domains.",
          "Re-skim every cheat sheet, especially Domain 1 and 2.",
        ] },
        Sat: { t: "Light review - do not cram", s: [
          "One 20-question mixed mock: tell Kiro 'give me a 20-question mixed mock.'",
          "Re-read the Exam-Day cheat sheet. Then stop early and rest.",
        ] },
        Sun: { t: "Rest before the exam", s: [
          "No new material. Skim the cheat sheets once if you want.",
          "Check exam logistics (ID, quiet room). Sleep well - the exam is tomorrow.",
        ] },
      },
    },
  ],

  // Compact in-app cheat sheets (full detail lives in /cheatsheets/*.md).
  cheatsheets: [
    {
      domain: 1, title: "FM Integration, Data & Compliance", weight: 31,
      remember: [
        "Converse API + always set maxTokens.",
        "RAG = look it up; fine-tune = retrain (LoRA = cheap fine-tune).",
        "Chunking + embeddings decide RAG quality.",
      ],
      points: [
        ["Bedrock", "One API to many FMs (Claude, Nova, Llama, Titan). Serverless, per-token."],
        ["Converse API", "Unified call for any chat model. Set maxTokens or you get throttled."],
        ["Cross-Region Inference", "us./eu. profile spreads calls across regions = fewer throttles."],
        ["RAG vs fine-tune", "Changing facts = RAG. Style/format/domain = fine-tune. LoRA = cheap fine-tune."],
        ["Vector store", "KB (easiest), OpenSearch (scale/hybrid), Aurora pgvector, S3 Vectors, DynamoDB."],
        ["Embeddings", "Titan V2. Turn text into meaning-vectors. More dims = better but pricier."],
        ["Chunking", "Fixed / semantic / hierarchical. Tables -> advanced FM-based parsing."],
        ["Prompt Mgmt / Flows", "Version prompts / chain them visually with branching."],
      ],
      traps: [
        "Unset maxTokens = random throttling (quota reservation, not rate).",
        "Fine-tuning when the need is current facts (that's RAG).",
        "Querying a KB before ingestion finishes = empty, not broken.",
      ],
    },
    {
      domain: 2, title: "Implementation & Integration", weight: 26,
      remember: [
        "New agents -> AgentCore, not classic Bedrock Agents.",
        "Match deployment to need (Lambda / provisioned / SageMaker).",
        "Resilience = backoff + retries + fallback + streaming.",
      ],
      points: [
        ["AgentCore", "Current agent platform: Harness (managed loop), Gateway (APIs as tools), Memory."],
        ["Bedrock Agents (classic)", "Deprecating — know conceptually, build new on AgentCore."],
        ["Strands / Agent Squad", "AWS frameworks for single + multi-agent systems."],
        ["MCP", "Universal plug for agent<->tool. MCP servers on Lambda (light) or ECS (heavy)."],
        ["Deployment", "Lambda=on-demand; provisioned throughput=steady high volume; SageMaker=self-host."],
        ["Streaming", "ConverseStream/SSE/WebSockets for fast time-to-first-token."],
        ["Routing", "Static rules vs dynamic (hard->big model, easy->cheap)."],
        ["Q Developer / Q Business", "AI coding assistant / enterprise RAG assistant."],
      ],
      traps: [
        "Classic Bedrock Agents for a NEW build -> use AgentCore.",
        "Provisioned throughput (Bedrock capacity) != SageMaker endpoint (self-hosted).",
        "Forgetting agent stopping conditions / guardrails.",
      ],
    },
    {
      domain: 3, title: "AI Safety, Security & Governance", weight: 20,
      remember: [
        "Guardrails filter input AND output — but PII masking is response-only.",
        "Layer defenses: Comprehend -> Guardrails -> Lambda.",
        "Governance = model cards + lineage + CloudTrail.",
      ],
      points: [
        ["Guardrails", "Filter words/topics/PII + contextual grounding (anti-hallucination)."],
        ["PII logging gap", "Guardrails masks the RESPONSE only; logs keep plaintext -> encrypt with KMS."],
        ["Comprehend vs Macie", "Comprehend = PII in text you send; Macie = PII at rest in S3."],
        ["Hallucination fix", "KB grounding + confidence scoring + JSON Schema."],
        ["Data security", "VPC endpoints/PrivateLink, IAM least privilege, Lake Formation."],
        ["Governance", "SageMaker model cards, Glue lineage/Catalog, CloudTrail, token redaction."],
        ["Responsible AI", "Agent tracing, Clarify bias metrics, A/B, LLM-as-a-judge."],
      ],
      traps: [
        "Masking the response but leaving PII in CloudWatch Logs (encrypt with KMS).",
        "Mixing up Comprehend (text) and Macie (S3).",
      ],
    },
    {
      domain: 4, title: "Operational Efficiency & Optimization", weight: 12,
      remember: [
        "Cost is mostly tokens — prune context, cap output.",
        "Caching + dynamic routing are the big savers.",
        "temperature/top_p/top_k control randomness (0 = factual).",
      ],
      points: [
        ["CountTokens", "Free API to estimate tokens BEFORE calling the model."],
        ["Context pruning", "Fewer/more-relevant RAG chunks; summarize old chat."],
        ["Prompt caching", "Cache the static prefix = cheaper/faster. Zero hits = fragmentation."],
        ["Semantic caching", "Reuse an answer when a new query means the same thing."],
        ["Dynamic routing", "Hard queries -> big model, easy -> cheap."],
        ["Latency", "Latency-optimized models, streaming, parallel requests."],
        ["Monitoring", "CloudWatch token metrics, Model Invocation Logs, anomaly detection, X-Ray."],
      ],
      traps: [
        "Prompt cache not working = dynamic content in the cached prefix.",
        "temperature 0 = deterministic; know the direction.",
      ],
    },
    {
      domain: 5, title: "Testing, Validation & Troubleshooting", weight: 11,
      remember: [
        "Know which metric measures what.",
        "Golden datasets + regression tests catch drift on every deploy.",
        "Most failures = context window, retrieval, or prompt.",
      ],
      points: [
        ["Metrics", "Relevance/accuracy/consistency/fluency. RAG: correctness/completeness/faithfulness."],
        ["ROUGE/BLEU/BERTScore", "ROUGE/BLEU = word overlap; BERTScore = meaning similarity."],
        ["Bedrock Model Evaluations", "Automated / human / LLM-as-a-judge against a dataset."],
        ["Agent evaluation", "Task completion, tool usage, reasoning quality."],
        ["A/B + canary", "Compare versions on real traffic; roll out slowly."],
        ["Troubleshoot", "Context overflow -> chunking; retrieval -> embeddings; prompt -> versions/schema."],
      ],
      traps: [
        "ROUGE = summarization overlap; faithfulness = grounded to retrieved context.",
        "Answer cut off = context-window overflow.",
      ],
    },
  ],

  flashcards: [
    { d: 1, q: "Converse API vs InvokeModel — which and why?", a: "Converse: one unified format across all Bedrock chat models. InvokeModel needs a different body per provider." },
    { d: 1, q: "Why must you set maxTokens?", a: "Unset reserves the model's max output, silently over-reserving quota -> random ThrottlingException." },
    { d: 1, q: "RAG or fine-tuning for facts that change weekly?", a: "RAG — just update the data source. Fine-tuning is for style/format/domain skill." },
    { d: 1, q: "What is LoRA?", a: "Cheap fine-tuning: trains a small adapter instead of the whole model." },
    { d: 1, q: "What does a cross-region inference profile do?", a: "Spreads calls across regions (us./eu. prefix) for higher availability and fewer throttles." },
    { d: 1, q: "Which embedding model for a KB?", a: "Amazon Titan Embeddings V2. Higher dimensions = more accurate but costlier." },
    { d: 1, q: "Three chunking strategies?", a: "Fixed, semantic, hierarchical. Table-heavy PDFs need advanced FM-based parsing." },
    { d: 1, q: "Easiest managed RAG path on AWS?", a: "Amazon Bedrock Knowledge Bases — point at S3, it handles retrieval." },
    { d: 1, q: "What is hybrid search + a reranker?", a: "Combine keyword + vector search, then a reranker re-sorts results by relevance." },
    { d: 2, q: "New agent build — classic Bedrock Agents or AgentCore?", a: "AgentCore. Classic Bedrock Agents is in maintenance mode / deprecating." },
    { d: 2, q: "What is an AgentCore Gateway?", a: "It exposes your REST APIs / Lambdas as tools an agent can call." },
    { d: 2, q: "What is MCP?", a: "Model Context Protocol — a universal interface for agent<->tool communication." },
    { d: 2, q: "Lambda vs provisioned throughput vs SageMaker endpoint?", a: "Lambda = on-demand; provisioned = steady high volume; SageMaker = self-hosted/custom model." },
    { d: 2, q: "Fix for slow first token in a chat UI?", a: "Response streaming (ConverseStream / SSE / WebSockets)." },
    { d: 2, q: "Which errors do you retry?", a: "Throttling, ModelTimeout, ServiceUnavailable, InternalServer. NOT Validation or AccessDenied." },
    { d: 2, q: "Outposts vs Wavelength?", a: "Outposts = AWS on-prem (data residency). Wavelength = edge/5G low latency." },
    { d: 3, q: "The Guardrails PII trap?", a: "Masking applies to the response only; unmasked PII still goes to CloudWatch Logs — encrypt with KMS." },
    { d: 3, q: "Comprehend vs Macie for PII?", a: "Comprehend = PII in text you send it; Macie = sensitive data at rest in S3." },
    { d: 3, q: "What is a contextual grounding check?", a: "A Guardrails feature measuring how well a response aligns with retrieved context (anti-hallucination)." },
    { d: 3, q: "Keep sensitive inference data off the public internet?", a: "VPC endpoints / PrivateLink." },
    { d: 3, q: "How to prove a model isn't biased?", a: "SageMaker Clarify bias metrics + model cards + agent tracing." },
    { d: 3, q: "Reduce hallucinations — three levers?", a: "Ground in a Knowledge Base, add confidence scoring, enforce JSON Schema output." },
    { d: 4, q: "What is CountTokens used for?", a: "Free API to estimate a prompt's token count before invoking the model." },
    { d: 4, q: "Why would prompt caching show zero hits?", a: "Cache fragmentation — the cached prefix changed (timestamps, whitespace, reordered JSON)." },
    { d: 4, q: "temperature 0 vs 1?", a: "0 = deterministic/factual; 1 = creative/random." },
    { d: 4, q: "Cheapest way to cut cost while keeping quality?", a: "Smaller model + RAG/tools, caching, and context pruning — plus dynamic routing." },
    { d: 5, q: "What does ROUGE measure?", a: "Word/phrase overlap with a reference answer (summarization/translation)." },
    { d: 5, q: "What is 'faithfulness' in RAG eval?", a: "How well the answer sticks to the retrieved context (grounding)." },
    { d: 5, q: "Catch quality regressions on deploy — how?", a: "Golden dataset + regression tests + canary/A-B before full rollout." },
    { d: 5, q: "'Answer got cut off' — likely cause?", a: "Context-window overflow / truncation — fix chunking or trim the prompt." },
  ],

  quiz: [
    { id: "q1", d: 1, type: "mcq",
      q: "Flat request volume but intermittent ThrottlingException on Claude in us-east-1. Latency isn't a concern. Best fix with least code?",
      options: ["Switch to InvokeModel + manual retries", "Move to a SageMaker endpoint", "Use a cross-region inference profile (us.) and set maxTokens explicitly", "Buy provisioned throughput"],
      answer: 2,
      explain: "Flat volume + throttling = unset maxTokens over-reserving quota + single-region limits. Set maxTokens + cross-region profile = no rewrite. Provisioned is overkill when latency isn't the issue." },
    { id: "q2", d: 1, type: "mrq",
      q: "RAG over table-heavy PDFs misses clauses and invents terms. Pick TWO fixes.",
      options: ["Increase maxTokens", "Advanced FM-based parsing + semantic/hierarchical chunking", "Add a Guardrails contextual grounding check", "Use a bigger embedding LLM", "Raise temperature to 0.9"],
      answer: [1, 2],
      explain: "FM parsing + better chunking fixes missed clauses; grounding check catches invented terms. maxTokens/temperature/embedding size don't address retrieval faithfulness." },
    { id: "q3", d: 3, type: "mcq",
      q: "Guardrails masks PII in responses, but an auditor finds patient IDs in plaintext. Where, and the fix?",
      options: ["Guardrails failed; raise filter strength", "CloudWatch Logs — masking is response-only; encrypt logs with KMS + restrict IAM", "Vector store; enable encryption", "S3 source; add a bucket policy"],
      answer: 1,
      explain: "Guardrails masks the response only; original input is logged in plaintext to CloudWatch. Encrypt log groups with KMS, restrict access, use Macie." },
    { id: "q4", d: 2, type: "mcq",
      q: "New autonomous agent calling internal REST APIs as tools, wants a managed loop with no orchestration code. Best today?",
      options: ["Classic Bedrock Agents + action groups", "AgentCore Harness + Gateway exposing the APIs as tools", "One Lambda that prompt-chains manually", "Q Business with plugins"],
      answer: 1,
      explain: "Classic Bedrock Agents is deprecating. AgentCore Harness = managed config loop; Gateway turns REST APIs into tools." },
    { id: "q5", d: 1, type: "self",
      q: "ORDER: put these RAG KB steps in order — (1) retrieval quality test, (2) create KB on S3, (3) choose chunking+embeddings, (4) start ingestion & wait, (5) prepare S3 docs.",
      answer: "5 -> 3 -> 2 -> 4 -> 1. Prepare docs, decide chunking/embeddings, create KB, ingest (querying before ingest = empty), then evaluate. No partial credit on ordering." },
    { id: "q6", d: 4, type: "self",
      q: "MATCH each symptom to the lever: (a) repeated identical system prompts inflating cost; (b) simple queries on an expensive model; (c) slow first token; (d) cost spikes from huge outputs.",
      answer: "a=prompt caching, b=dynamic/intelligent routing, c=latency-optimized model + streaming, d=response size controls / maxTokens." },
    { id: "q7", d: 1, type: "mcq",
      q: "A team needs the model to answer in the company's brand tone and format consistently, with no changing facts involved. Best approach?",
      options: ["RAG with a Knowledge Base", "Fine-tuning (e.g. LoRA)", "Raise temperature", "Add more few-shot examples every call"],
      answer: 1,
      explain: "Style/tone/format that's stable = fine-tuning (LoRA is the cheap route). RAG is for changing/proprietary facts, not tone." },
    { id: "q8", d: 4, type: "mcq",
      q: "Which best reduces cost with least quality loss for a high-volume assistant?",
      options: ["Always use the largest model", "Smaller model + RAG, prompt caching, and context pruning", "Raise maxTokens", "Disable monitoring"],
      answer: 1,
      explain: "Let RAG/tools carry the load on a smaller model, cache the static prefix, prune context. Bigger model/maxTokens raise cost." },
    { id: "q9", d: 3, type: "mrq",
      q: "Pick TWO valid defenses against prompt injection / jailbreaks.",
      options: ["Input sanitization + injection/jailbreak detection", "Higher temperature", "Safety classifiers on inputs", "Remove maxTokens", "Disable Guardrails"],
      answer: [0, 2],
      explain: "Sanitization + detection and safety classifiers defend against adversarial input. The others do nothing or hurt." },
    { id: "q10", d: 5, type: "mcq",
      q: "After a model update, answer quality quietly dropped. Which practice would have caught it before release?",
      options: ["Higher temperature", "Regression testing against a golden dataset + canary rollout", "Bigger context window", "More maxTokens"],
      answer: 1,
      explain: "Golden-dataset regression tests + canary catch semantic drift/quality drops before full rollout." },
    { id: "q11", d: 2, type: "mcq",
      q: "A chat UI feels laggy because users wait for the whole answer. Cheapest fix?",
      options: ["Bigger instance", "Response streaming (ConverseStream)", "Provisioned throughput", "Switch to InvokeModel"],
      answer: 1,
      explain: "Streaming delivers tokens as generated, cutting time-to-first-token. No infra change needed." },
    { id: "q12", d: 3, type: "mcq",
      q: "You must detect and redact PII in free-text support tickets before they reach the model. Best service?",
      options: ["Macie", "Comprehend", "Rekognition", "Textract"],
      answer: 1,
      explain: "Comprehend does NER/PII detection on text you pass it. Macie scans S3 at rest; different job." },
    { id: "q13", d: 1, type: "mcq",
      q: "Which is TRUE about Bedrock Knowledge Bases ingestion?",
      options: ["Queries work during ingestion", "Querying before ingestion completes returns empty results", "Ingestion is instant", "It needs no embedding model"],
      answer: 1,
      explain: "Query before ingestion finishes = empty (not an error). KBs need an embedding model + vector store." },
    { id: "q14", d: 4, type: "mcq",
      q: "For a factual Q&A assistant, what temperature setting fits best?",
      options: ["1.0 for creativity", "0 (or near 0) for deterministic answers", "It has no effect", "Always 0.7"],
      answer: 1,
      explain: "Low temperature = deterministic/factual output; high temperature = creative/random." },
    { id: "q15", d: 5, type: "mcq",
      q: "Which metric best evaluates a summarization model against reference summaries?",
      options: ["ROUGE", "Latency", "Token count", "Class Imbalance"],
      answer: 0,
      explain: "ROUGE measures overlap with reference text (summarization/translation). Class Imbalance is a Clarify bias metric." },
    { id: "q16", d: 2, type: "mrq",
      q: "Pick TWO good resilience patterns for FM API calls.",
      options: ["Exponential backoff with adaptive retry", "Retry AccessDeniedException", "Fallback model on failure", "Remove all timeouts", "Retry ValidationException"],
      answer: [0, 2],
      explain: "Backoff/adaptive retry + a fallback path are resilient. Don't retry AccessDenied/Validation — they won't succeed." },
    { id: "q17", d: 3, type: "mcq",
      q: "Sensitive fine-tuning data must never traverse the public internet to Bedrock. What do you use?",
      options: ["A NAT gateway", "VPC endpoints / PrivateLink", "A public S3 bucket", "CloudFront"],
      answer: 1,
      explain: "PrivateLink / VPC endpoints keep traffic on the AWS private network." },
    { id: "q18", d: 1, type: "mcq",
      q: "You need a vector store and you're already running PostgreSQL on Aurora. Lowest-friction option?",
      options: ["Migrate everything to OpenSearch", "Aurora with the pgvector extension", "DynamoDB", "S3 Glacier"],
      answer: 1,
      explain: "pgvector adds vector search to your existing Aurora Postgres — least friction. Glacier is archival, not a vector store." },
  ],
};
