/* AIP-C01 Study Hub — content data.
   Loaded as a global (no fetch) so the app works from file:// on any device, offline.
   Grow it by asking Kiro: "add 20 quiz questions and 15 flashcards to the app." */
window.DATA = {
  exam: {
    name: "AWS Certified Generative AI Developer – Professional",
    code: "AIP-C01",
    date: "2026-10-19",
    start: "2026-09-05",
    questions: 75,
    minutes: 180,
    pass: 750,
  },

  domains: [
    { id: 1, name: "FM Integration, Data & Compliance", weight: 31 },
    { id: 2, name: "Implementation & Integration", weight: 26 },
    { id: 3, name: "AI Safety, Security & Governance", weight: 20 },
    { id: 4, name: "Operational Efficiency & Optimization", weight: 12 },
    { id: 5, name: "Testing, Validation & Troubleshooting", weight: 11 },
  ],

  // Week blocks. The app finds today's date within a week and shows that day's task.
  weeks: [
    {
      n: 0, label: "Setup", start: "2026-09-05", end: "2026-09-06",
      focus: "Get set up + baseline", udemy: "Section 1 (start)", lab: "Lab 1: Converse API",
      days: {
        Fri: "Read START-HERE + blueprint. Enable Bedrock model access.",
        Sat: "Do Lab 1 (Converse API). Take Practice Exam 1 as a diagnostic — expect a low score.",
        Sun: "Review diagnostic. Log weak areas. Watch Section 1 intro videos.",
      },
    },
    {
      n: 1, label: "Domain 1a", start: "2026-09-07", end: "2026-09-13",
      focus: "Bedrock, model selection, data pipelines", udemy: "Section 1 + start Section 2",
      lab: "Extend Lab 1 (compare models)",
      days: {
        Mon: "Heavy: FMs on Bedrock + Converse vs InvokeModel. Extend Lab 1.",
        Tue: "Model selection + cost/capability tradeoffs. Quiz 5 (D1).",
        Wed: "Resilience: Cross-Region Inference + Step Functions circuit breaker. Quiz 5.",
        Thu: "Fine-tuning vs RAG, LoRA, SageMaker Model Registry. Quiz 5.",
        Fri: "Data pipelines: Glue, Data Wrangler, Transcribe, Comprehend. Quiz 5.",
        Sat: "Catch up + re-read shaky topics. Quiz 5.",
        Sun: "Weak-area drill + 15-Q Domain 1a mini-mock. Update tracker.",
      },
    },
    {
      n: 2, label: "Domain 1b", start: "2026-09-14", end: "2026-09-20",
      focus: "RAG, vector stores, retrieval, prompts", udemy: "Finish Section 2",
      lab: "Lab 2: RAG Knowledge Base",
      days: {
        Mon: "Heavy: Lab 2 — build a Bedrock RAG Knowledge Base.",
        Tue: "Vector stores: KB, OpenSearch, Aurora pgvector, S3 Vectors, DynamoDB. Quiz 5.",
        Wed: "Chunking (fixed/semantic/hierarchical) + embeddings (Titan V2). Quiz 5.",
        Thu: "Hybrid search + rerankers + query expansion. Quiz 5.",
        Fri: "Prompt engineering + Bedrock Prompt Management. Quiz 5.",
        Sat: "Bedrock Prompt Flows (chains + branching). Quiz 5.",
        Sun: "Weak-area drill + 25-Q full Domain 1 mock. Update tracker.",
      },
    },
    {
      n: 3, label: "Domain 2", start: "2026-09-21", end: "2026-09-27",
      focus: "Agents, deployment, integration", udemy: "Sections 3, 5, 6",
      lab: "Lab 3: Agent on AgentCore",
      days: {
        Mon: "Heavy: Lab 3 — build an agent (AgentCore Harness + Gateway tool).",
        Tue: "Strands, Agent Squad, MCP, ReAct via Step Functions. Quiz 5.",
        Wed: "Agent safety + deployment (Lambda/provisioned/SageMaker). Quiz 5.",
        Thu: "FM API integration: streaming, backoff, routing. Quiz 5.",
        Fri: "Enterprise integration: API GW + EventBridge, Outposts/Wavelength, CI/CD. Quiz 5.",
        Sat: "Amplify, Q Developer, Q Business, BDA. Quiz 5.",
        Sun: "Weak-area drill + 20-Q Domain 2 mock. Milestone: 57% covered.",
      },
    },
    {
      n: 4, label: "Domain 3", start: "2026-09-28", end: "2026-10-04",
      focus: "Safety, security, governance", udemy: "Sections 7 (part) + 8",
      lab: "Lab 4: Guardrails + PII",
      days: {
        Mon: "Heavy: Lab 4 — Guardrails + Comprehend/Macie PII + the CloudWatch KMS fix.",
        Tue: "Guardrails, custom moderation, prompt-injection defense. Quiz 5.",
        Wed: "Hallucination reduction (grounding, confidence, JSON schema). Quiz 5.",
        Thu: "Data security: VPC endpoints, IAM, Lake Formation, PII. Quiz 5.",
        Fri: "Governance: model cards, Glue lineage, CloudTrail, redaction. Quiz 5.",
        Sat: "Responsible AI: tracing, fairness/Clarify, LLM-as-judge. Quiz 5.",
        Sun: "Weak-area drill + 20-Q Domain 3 mock. Update tracker.",
      },
    },
    {
      n: 5, label: "Domains 4 + 5", start: "2026-10-05", end: "2026-10-11",
      focus: "Optimize, monitor, evaluate, troubleshoot", udemy: "Sections 4, 7, 9",
      lab: "Lab 5: Evaluate + observe + break/fix",
      days: {
        Mon: "Heavy: Lab 5 — Model Evaluations + CloudWatch/X-Ray + deliberately break/fix.",
        Tue: "Token/cost efficiency: CountTokens, pruning, response limits. Quiz 5.",
        Wed: "Caching + latency + temperature/top-k/top-p. Quiz 5.",
        Thu: "Monitoring: CloudWatch, Model Invocation Logs, anomaly, X-Ray. Quiz 5.",
        Fri: "Evaluation: Bedrock Model Evaluations, RAG eval, LLM-as-judge, ROUGE. Quiz 5.",
        Sat: "Troubleshooting: context window, retrieval, prompts, schema. Quiz 5.",
        Sun: "Weak-area drill + 15-Q D4+D5 mock. All 5 domains covered.",
      },
    },
    {
      n: 6, label: "Mocks + Review", start: "2026-10-12", end: "2026-10-18",
      focus: "Practice exams + close gaps", udemy: "Practice Exams 1 & 2 + section quizzes",
      lab: "None — exam prep",
      days: {
        Mon: "Full 75-Q timed mock (Practice Exam). Log every miss.",
        Tue: "Remediate the mock with Kiro. Re-drill misses.",
        Wed: "Second full 75-Q timed mock (Practice Exam 2). Log misses.",
        Thu: "Remediate mock 2. Drill ordering + matching questions.",
        Fri: "Targeted weak-area drills across all domains. Re-skim blueprint.",
        Sat: "Light review: 20-Q mixed mock + cheat sheets. Stop early.",
        Sun: "Rest. Skim cheat sheets. Sleep well. Exam is tomorrow.",
      },
    },
  ],

  // Compact in-app cheat sheets (full detail lives in /cheatsheets/*.md).
  cheatsheets: [
    {
      domain: 1, title: "FM Integration, Data & Compliance", weight: 31,
      remember: [
        "Converse API + always set maxTokens.",
        "RAG = look it up; fine-tune = retrain (LoRA = cheap fine-tune).",
        "Chunking + embeddings decide RAG quality.",
      ],
      points: [
        ["Bedrock", "One API to many FMs (Claude, Nova, Llama, Titan). Serverless, per-token."],
        ["Converse API", "Unified call for any chat model. Set maxTokens or you get throttled."],
        ["Cross-Region Inference", "us./eu. profile spreads calls across regions = fewer throttles."],
        ["RAG vs fine-tune", "Changing facts = RAG. Style/format/domain = fine-tune. LoRA = cheap fine-tune."],
        ["Vector store", "KB (easiest), OpenSearch (scale/hybrid), Aurora pgvector, S3 Vectors, DynamoDB."],
        ["Embeddings", "Titan V2. Turn text into meaning-vectors. More dims = better but pricier."],
        ["Chunking", "Fixed / semantic / hierarchical. Tables -> advanced FM-based parsing."],
        ["Prompt Mgmt / Flows", "Version prompts / chain them visually with branching."],
      ],
      traps: [
        "Unset maxTokens = random throttling (quota reservation, not rate).",
        "Fine-tuning when the need is current facts (that's RAG).",
        "Querying a KB before ingestion finishes = empty, not broken.",
      ],
    },
    {
      domain: 2, title: "Implementation & Integration", weight: 26,
      remember: [
        "New agents -> AgentCore, not classic Bedrock Agents.",
        "Match deployment to need (Lambda / provisioned / SageMaker).",
        "Resilience = backoff + retries + fallback + streaming.",
      ],
      points: [
        ["AgentCore", "Current agent platform: Harness (managed loop), Gateway (APIs as tools), Memory."],
        ["Bedrock Agents (classic)", "Deprecating — know conceptually, build new on AgentCore."],
        ["Strands / Agent Squad", "AWS frameworks for single + multi-agent systems."],
        ["MCP", "Universal plug for agent<->tool. MCP servers on Lambda (light) or ECS (heavy)."],
        ["Deployment", "Lambda=on-demand; provisioned throughput=steady high volume; SageMaker=self-host."],
        ["Streaming", "ConverseStream/SSE/WebSockets for fast time-to-first-token."],
        ["Routing", "Static rules vs dynamic (hard->big model, easy->cheap)."],
        ["Q Developer / Q Business", "AI coding assistant / enterprise RAG assistant."],
      ],
      traps: [
        "Classic Bedrock Agents for a NEW build -> use AgentCore.",
        "Provisioned throughput (Bedrock capacity) != SageMaker endpoint (self-hosted).",
        "Forgetting agent stopping conditions / guardrails.",
      ],
    },
    {
      domain: 3, title: "AI Safety, Security & Governance", weight: 20,
      remember: [
        "Guardrails filter input AND output — but PII masking is response-only.",
        "Layer defenses: Comprehend -> Guardrails -> Lambda.",
        "Governance = model cards + lineage + CloudTrail.",
      ],
      points: [
        ["Guardrails", "Filter words/topics/PII + contextual grounding (anti-hallucination)."],
        ["PII logging gap", "Guardrails masks the RESPONSE only; logs keep plaintext -> encrypt with KMS."],
        ["Comprehend vs Macie", "Comprehend = PII in text you send; Macie = PII at rest in S3."],
        ["Hallucination fix", "KB grounding + confidence scoring + JSON Schema."],
        ["Data security", "VPC endpoints/PrivateLink, IAM least privilege, Lake Formation."],
        ["Governance", "SageMaker model cards, Glue lineage/Catalog, CloudTrail, token redaction."],
        ["Responsible AI", "Agent tracing, Clarify bias metrics, A/B, LLM-as-a-judge."],
      ],
      traps: [
        "Masking the response but leaving PII in CloudWatch Logs (encrypt with KMS).",
        "Mixing up Comprehend (text) and Macie (S3).",
      ],
    },
    {
      domain: 4, title: "Operational Efficiency & Optimization", weight: 12,
      remember: [
        "Cost is mostly tokens — prune context, cap output.",
        "Caching + dynamic routing are the big savers.",
        "temperature/top_p/top_k control randomness (0 = factual).",
      ],
      points: [
        ["CountTokens", "Free API to estimate tokens BEFORE calling the model."],
        ["Context pruning", "Fewer/more-relevant RAG chunks; summarize old chat."],
        ["Prompt caching", "Cache the static prefix = cheaper/faster. Zero hits = fragmentation."],
        ["Semantic caching", "Reuse an answer when a new query means the same thing."],
        ["Dynamic routing", "Hard queries -> big model, easy -> cheap."],
        ["Latency", "Latency-optimized models, streaming, parallel requests."],
        ["Monitoring", "CloudWatch token metrics, Model Invocation Logs, anomaly detection, X-Ray."],
      ],
      traps: [
        "Prompt cache not working = dynamic content in the cached prefix.",
        "temperature 0 = deterministic; know the direction.",
      ],
    },
    {
      domain: 5, title: "Testing, Validation & Troubleshooting", weight: 11,
      remember: [
        "Know which metric measures what.",
        "Golden datasets + regression tests catch drift on every deploy.",
        "Most failures = context window, retrieval, or prompt.",
      ],
      points: [
        ["Metrics", "Relevance/accuracy/consistency/fluency. RAG: correctness/completeness/faithfulness."],
        ["ROUGE/BLEU/BERTScore", "ROUGE/BLEU = word overlap; BERTScore = meaning similarity."],
        ["Bedrock Model Evaluations", "Automated / human / LLM-as-a-judge against a dataset."],
        ["Agent evaluation", "Task completion, tool usage, reasoning quality."],
        ["A/B + canary", "Compare versions on real traffic; roll out slowly."],
        ["Troubleshoot", "Context overflow -> chunking; retrieval -> embeddings; prompt -> versions/schema."],
      ],
      traps: [
        "ROUGE = summarization overlap; faithfulness = grounded to retrieved context.",
        "Answer cut off = context-window overflow.",
      ],
    },
  ],

  flashcards: [
    { d: 1, q: "Converse API vs InvokeModel — which and why?", a: "Converse: one unified format across all Bedrock chat models. InvokeModel needs a different body per provider." },
    { d: 1, q: "Why must you set maxTokens?", a: "Unset reserves the model's max output, silently over-reserving quota -> random ThrottlingException." },
    { d: 1, q: "RAG or fine-tuning for facts that change weekly?", a: "RAG — just update the data source. Fine-tuning is for style/format/domain skill." },
    { d: 1, q: "What is LoRA?", a: "Cheap fine-tuning: trains a small adapter instead of the whole model." },
    { d: 1, q: "What does a cross-region inference profile do?", a: "Spreads calls across regions (us./eu. prefix) for higher availability and fewer throttles." },
    { d: 1, q: "Which embedding model for a KB?", a: "Amazon Titan Embeddings V2. Higher dimensions = more accurate but costlier." },
    { d: 1, q: "Three chunking strategies?", a: "Fixed, semantic, hierarchical. Table-heavy PDFs need advanced FM-based parsing." },
    { d: 1, q: "Easiest managed RAG path on AWS?", a: "Amazon Bedrock Knowledge Bases — point at S3, it handles retrieval." },
    { d: 1, q: "What is hybrid search + a reranker?", a: "Combine keyword + vector search, then a reranker re-sorts results by relevance." },
    { d: 2, q: "New agent build — classic Bedrock Agents or AgentCore?", a: "AgentCore. Classic Bedrock Agents is in maintenance mode / deprecating." },
    { d: 2, q: "What is an AgentCore Gateway?", a: "It exposes your REST APIs / Lambdas as tools an agent can call." },
    { d: 2, q: "What is MCP?", a: "Model Context Protocol — a universal interface for agent<->tool communication." },
    { d: 2, q: "Lambda vs provisioned throughput vs SageMaker endpoint?", a: "Lambda = on-demand; provisioned = steady high volume; SageMaker = self-hosted/custom model." },
    { d: 2, q: "Fix for slow first token in a chat UI?", a: "Response streaming (ConverseStream / SSE / WebSockets)." },
    { d: 2, q: "Which errors do you retry?", a: "Throttling, ModelTimeout, ServiceUnavailable, InternalServer. NOT Validation or AccessDenied." },
    { d: 2, q: "Outposts vs Wavelength?", a: "Outposts = AWS on-prem (data residency). Wavelength = edge/5G low latency." },
    { d: 3, q: "The Guardrails PII trap?", a: "Masking applies to the response only; unmasked PII still goes to CloudWatch Logs — encrypt with KMS." },
    { d: 3, q: "Comprehend vs Macie for PII?", a: "Comprehend = PII in text you send it; Macie = sensitive data at rest in S3." },
    { d: 3, q: "What is a contextual grounding check?", a: "A Guardrails feature measuring how well a response aligns with retrieved context (anti-hallucination)." },
    { d: 3, q: "Keep sensitive inference data off the public internet?", a: "VPC endpoints / PrivateLink." },
    { d: 3, q: "How to prove a model isn't biased?", a: "SageMaker Clarify bias metrics + model cards + agent tracing." },
    { d: 3, q: "Reduce hallucinations — three levers?", a: "Ground in a Knowledge Base, add confidence scoring, enforce JSON Schema output." },
    { d: 4, q: "What is CountTokens used for?", a: "Free API to estimate a prompt's token count before invoking the model." },
    { d: 4, q: "Why would prompt caching show zero hits?", a: "Cache fragmentation — the cached prefix changed (timestamps, whitespace, reordered JSON)." },
    { d: 4, q: "temperature 0 vs 1?", a: "0 = deterministic/factual; 1 = creative/random." },
    { d: 4, q: "Cheapest way to cut cost while keeping quality?", a: "Smaller model + RAG/tools, caching, and context pruning — plus dynamic routing." },
    { d: 5, q: "What does ROUGE measure?", a: "Word/phrase overlap with a reference answer (summarization/translation)." },
    { d: 5, q: "What is 'faithfulness' in RAG eval?", a: "How well the answer sticks to the retrieved context (grounding)." },
    { d: 5, q: "Catch quality regressions on deploy — how?", a: "Golden dataset + regression tests + canary/A-B before full rollout." },
    { d: 5, q: "'Answer got cut off' — likely cause?", a: "Context-window overflow / truncation — fix chunking or trim the prompt." },
  ],

  quiz: [
    { id: "q1", d: 1, type: "mcq",
      q: "Flat request volume but intermittent ThrottlingException on Claude in us-east-1. Latency isn't a concern. Best fix with least code?",
      options: ["Switch to InvokeModel + manual retries", "Move to a SageMaker endpoint", "Use a cross-region inference profile (us.) and set maxTokens explicitly", "Buy provisioned throughput"],
      answer: 2,
      explain: "Flat volume + throttling = unset maxTokens over-reserving quota + single-region limits. Set maxTokens + cross-region profile = no rewrite. Provisioned is overkill when latency isn't the issue." },
    { id: "q2", d: 1, type: "mrq",
      q: "RAG over table-heavy PDFs misses clauses and invents terms. Pick TWO fixes.",
      options: ["Increase maxTokens", "Advanced FM-based parsing + semantic/hierarchical chunking", "Add a Guardrails contextual grounding check", "Use a bigger embedding LLM", "Raise temperature to 0.9"],
      answer: [1, 2],
      explain: "FM parsing + better chunking fixes missed clauses; grounding check catches invented terms. maxTokens/temperature/embedding size don't address retrieval faithfulness." },
    { id: "q3", d: 3, type: "mcq",
      q: "Guardrails masks PII in responses, but an auditor finds patient IDs in plaintext. Where, and the fix?",
      options: ["Guardrails failed; raise filter strength", "CloudWatch Logs — masking is response-only; encrypt logs with KMS + restrict IAM", "Vector store; enable encryption", "S3 source; add a bucket policy"],
      answer: 1,
      explain: "Guardrails masks the response only; original input is logged in plaintext to CloudWatch. Encrypt log groups with KMS, restrict access, use Macie." },
    { id: "q4", d: 2, type: "mcq",
      q: "New autonomous agent calling internal REST APIs as tools, wants a managed loop with no orchestration code. Best today?",
      options: ["Classic Bedrock Agents + action groups", "AgentCore Harness + Gateway exposing the APIs as tools", "One Lambda that prompt-chains manually", "Q Business with plugins"],
      answer: 1,
      explain: "Classic Bedrock Agents is deprecating. AgentCore Harness = managed config loop; Gateway turns REST APIs into tools." },
    { id: "q5", d: 1, type: "self",
      q: "ORDER: put these RAG KB steps in order — (1) retrieval quality test, (2) create KB on S3, (3) choose chunking+embeddings, (4) start ingestion & wait, (5) prepare S3 docs.",
      answer: "5 -> 3 -> 2 -> 4 -> 1. Prepare docs, decide chunking/embeddings, create KB, ingest (querying before ingest = empty), then evaluate. No partial credit on ordering." },
    { id: "q6", d: 4, type: "self",
      q: "MATCH each symptom to the lever: (a) repeated identical system prompts inflating cost; (b) simple queries on an expensive model; (c) slow first token; (d) cost spikes from huge outputs.",
      answer: "a=prompt caching, b=dynamic/intelligent routing, c=latency-optimized model + streaming, d=response size controls / maxTokens." },
    { id: "q7", d: 1, type: "mcq",
      q: "A team needs the model to answer in the company's brand tone and format consistently, with no changing facts involved. Best approach?",
      options: ["RAG with a Knowledge Base", "Fine-tuning (e.g. LoRA)", "Raise temperature", "Add more few-shot examples every call"],
      answer: 1,
      explain: "Style/tone/format that's stable = fine-tuning (LoRA is the cheap route). RAG is for changing/proprietary facts, not tone." },
    { id: "q8", d: 4, type: "mcq",
      q: "Which best reduces cost with least quality loss for a high-volume assistant?",
      options: ["Always use the largest model", "Smaller model + RAG, prompt caching, and context pruning", "Raise maxTokens", "Disable monitoring"],
      answer: 1,
      explain: "Let RAG/tools carry the load on a smaller model, cache the static prefix, prune context. Bigger model/maxTokens raise cost." },
    { id: "q9", d: 3, type: "mrq",
      q: "Pick TWO valid defenses against prompt injection / jailbreaks.",
      options: ["Input sanitization + injection/jailbreak detection", "Higher temperature", "Safety classifiers on inputs", "Remove maxTokens", "Disable Guardrails"],
      answer: [0, 2],
      explain: "Sanitization + detection and safety classifiers defend against adversarial input. The others do nothing or hurt." },
    { id: "q10", d: 5, type: "mcq",
      q: "After a model update, answer quality quietly dropped. Which practice would have caught it before release?",
      options: ["Higher temperature", "Regression testing against a golden dataset + canary rollout", "Bigger context window", "More maxTokens"],
      answer: 1,
      explain: "Golden-dataset regression tests + canary catch semantic drift/quality drops before full rollout." },
    { id: "q11", d: 2, type: "mcq",
      q: "A chat UI feels laggy because users wait for the whole answer. Cheapest fix?",
      options: ["Bigger instance", "Response streaming (ConverseStream)", "Provisioned throughput", "Switch to InvokeModel"],
      answer: 1,
      explain: "Streaming delivers tokens as generated, cutting time-to-first-token. No infra change needed." },
    { id: "q12", d: 3, type: "mcq",
      q: "You must detect and redact PII in free-text support tickets before they reach the model. Best service?",
      options: ["Macie", "Comprehend", "Rekognition", "Textract"],
      answer: 1,
      explain: "Comprehend does NER/PII detection on text you pass it. Macie scans S3 at rest; different job." },
    { id: "q13", d: 1, type: "mcq",
      q: "Which is TRUE about Bedrock Knowledge Bases ingestion?",
      options: ["Queries work during ingestion", "Querying before ingestion completes returns empty results", "Ingestion is instant", "It needs no embedding model"],
      answer: 1,
      explain: "Query before ingestion finishes = empty (not an error). KBs need an embedding model + vector store." },
    { id: "q14", d: 4, type: "mcq",
      q: "For a factual Q&A assistant, what temperature setting fits best?",
      options: ["1.0 for creativity", "0 (or near 0) for deterministic answers", "It has no effect", "Always 0.7"],
      answer: 1,
      explain: "Low temperature = deterministic/factual output; high temperature = creative/random." },
    { id: "q15", d: 5, type: "mcq",
      q: "Which metric best evaluates a summarization model against reference summaries?",
      options: ["ROUGE", "Latency", "Token count", "Class Imbalance"],
      answer: 0,
      explain: "ROUGE measures overlap with reference text (summarization/translation). Class Imbalance is a Clarify bias metric." },
    { id: "q16", d: 2, type: "mrq",
      q: "Pick TWO good resilience patterns for FM API calls.",
      options: ["Exponential backoff with adaptive retry", "Retry AccessDeniedException", "Fallback model on failure", "Remove all timeouts", "Retry ValidationException"],
      answer: [0, 2],
      explain: "Backoff/adaptive retry + a fallback path are resilient. Don't retry AccessDenied/Validation — they won't succeed." },
    { id: "q17", d: 3, type: "mcq",
      q: "Sensitive fine-tuning data must never traverse the public internet to Bedrock. What do you use?",
      options: ["A NAT gateway", "VPC endpoints / PrivateLink", "A public S3 bucket", "CloudFront"],
      answer: 1,
      explain: "PrivateLink / VPC endpoints keep traffic on the AWS private network." },
    { id: "q18", d: 1, type: "mcq",
      q: "You need a vector store and you're already running PostgreSQL on Aurora. Lowest-friction option?",
      options: ["Migrate everything to OpenSearch", "Aurora with the pgvector extension", "DynamoDB", "S3 Glacier"],
      answer: 1,
      explain: "pgvector adds vector search to your existing Aurora Postgres — least friction. Glacier is archival, not a vector store." },
  ],
};
